# Generated by Django 4.2.7 on 2023-12-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
    ]
